name: "portfolio_tracking"
version: "1.0.0"
config-version: 2
profile: "default"
model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  portfolio_tracking:
    +materialized: view

    staging: # Data storage layer
      +materialized: view
      +schema: STAGING

    refined: # Refined data layer
      +materialized: table
      +schema: REFINED

    marts: # Data delivery layer
      +materialized: table
      +schema: MART_PORTFOLIO

snapshots:
  portfolio_tracking:
    +target_schema: SNAPSHOTS

seeds:
  +schema: seed_data
  portfolio_tracking:
    ABC_Bank_SECURITY_INFO:
      +column_types:
        LOAD_TS: TIMESTAMP
      +post-hook:
        - "UPDATE {{ this }} SET LOAD_TS = '{{ run_started_at }}' WHERE LOAD_TS IS NULL"


