SELECT
    CASE DATA_TYPE
        WHEN 'TEXT' THEN IFF(ENDSWITH(COLUMN_NAME, '_CODE'), ', ''-1''', 'Missing')
        WHEN 'NUMBER' THEN ', -1'
        WHEN 'DATE' THEN ', ''2000-01-01'''
        WHEN 'TIMESTAMP_NTZ' THEN ', ''2000-01-01'''
        ELSE ', ''Missing'''
    END || ' as ' || COLUMN_NAME as SQL_TEXT
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = 'KE_STAGING'
    AND TABLE_NAME = 'STG_ABC_BANK_POSITION'
ORDER BY
    ORDINAL_POSITION