SELECT
    ', ' || COLUMN_NAME || ' as ' || COLUMN_NAME || ' -- ' || DATA_TYPE
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = 'KE_SEED_DATA'
    AND TABLE_NAME = 'CURRENCY'
ORDER BY
    ORDINAL_POSITION