SELECT
    COLUMN_NAME || ' as ' || COLUMN_NAME || ' -- ' || DATA_TYPE
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = 'SOURCE_DATA'
    AND TABLE_NAME = 'ABC_BANK_POSITION'
ORDER BY
    ORDINAL_POSITION