with position_with_prev as (
    SELECT
        *
        , LAG(QUANTITY) OVER (PARTITION BY POSITION_HKEY ORDER BY LOAD_TS_UTC) as PREV_QUANTITY
    FROM {{ ref('HIST_ABC_BANK_POSITION_WITH_CLOSING') }}
),
calc as (
    SELECT
        *
        , IFF(PREV_QUANTITY IS NULL, QUANTITY, QUANTITY - PREV_QUANTITY) as QUANTITY_PURCHACED
    FROM position_with_prev
)
SELECT
    * EXCLUDE(PREV_QUANTITY)
    , CASE WHEN QUANTITY_PURCHACED >  0 THEN 'BUY'
           WHEN QUANTITY_PURCHACED = 0 THEN 'UNCHANGED'
           ELSE 'SELL' END as TX_TYPE
FROM calc
